spring:
    datasource:
      url: jdcb:h2:mem:testdb-${random.uuid}
      driver-class-name: org.h2.Driver
      username: sa
      passowrd:

      jpa:
        hibernate:
          dll-auto: create-drop

        flyway:
          enabled: false
